### ISSUE TITLE
bilibili is not working

### ISSUE THREAD

**Issue by toyqiu** [splitbrain/dokuwiki-plugin-vshare#100]
bilibili is not working

{{bilibili>L -BV1aR4y1j78Q}}
{{youtube>L-WM8YxwqEU}}

youtube player is working perfectly.

**Comment by splitbrain** [comment]
> `{{bilibili>L -BV1aR4y1j78Q}}`

I think that's wrong. I assume you meant `{{bilibili>BV1aR4y1j78Q}}` and that's working fine
