### ISSUE TITLE
Add proxied preview image, when GDPR option is enabled

### ISSUE THREAD

**Issue by saerdnaer** [splitbrain/dokuwiki-plugin-vshare#112]
When enabling the GDPR option, the white box is not really appealing...
![0E5933E0-C04A-4294-9FF5-3B1010399EBA](https://user-images.githubusercontent.com/40266/211213683-6e2b883e-e0d9-4992-84e2-0e7205b05762.jpeg)

Can the existing image proxy/caching mechanism be used to display the video thumbnail, without exposing the user's IP address? What would be the proper starting points to implement that feature? 

Would it acceptable to use an existing library to fetch the thumbnail image via oembed/opengraph/etc. or should that source code be self containted?

Related: https://github.com/splitbrain/dokuwiki-plugin-vshare/issues/28

**Comment by splitbrain** [comment]
Querying oembed feels way out of scope for this plugin. In fact oembed would be the more versatile, maybe more modern approach to implement what this plugin does. I believe there is an existing oembed plugin you could try.
