### ISSUE TITLE
Error loading plugin vshare

### ISSUE THREAD

**Issue by dave-fargo** [splitbrain/dokuwiki-plugin-vshare#132]
This error message is being displayed:

Error loading plugin vshare
ParseError: syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM)
More info is available in the error log.

I can share the error log info privately, if desired.

**Comment by splitbrain** [comment]
php too old?

**Comment by dave-fargo** [comment]
This install is 7.2.34

What's required?

**Comment by splitbrain** [comment]
7.4
