### ISSUE TITLE
Caption on video not appearing?

### ISSUE THREAD

**Issue by amulheirn** [splitbrain/dokuwiki-plugin-vshare#33]
I think the caption may not be working, but I'm not sure. Here is my wikitext:

{{ youtube>2ovSQ4bl4yM?small&Rel=0 |COB6008 a Racing Cobra }}

This appears to produce the video centred on the screen, but no caption other than the one that Youtube apply.

So I have to write text above the embedded video, but the spacing on the page makes the text look like the caption for the video _above_ it, which is confusing to the user.

I am using Detritus - please let me know if you have any additional info requirements about my setup.

Otherwise, I love the plugin!

**Comment by tmo26** [comment]
I can confirm, this is still the case with
Release 2018-04-22a "Greebo"
vshare plugin 2018-02-05

A fix would be appreciated.

**Comment by splitbrain** [comment]
titles are only used as fallback when the iframe doesn't load. similar to the image syntax.
