### ISSUE TITLE
Declaration Errors Received Upon Installation

### ISSUE THREAD

**Issue by MOEditor** [splitbrain/dokuwiki-plugin-vshare#34]
I receive the following errors after installing:

  * Warning: Declaration of syntax_plugin_vshare::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\xampp\htdocs\dokuwiki\lib\plugins\vshare\syntax.php on line 209

  * Warning: Declaration of syntax_plugin_vshare::render($mode, &$R, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\xampp\htdocs\dokuwiki\lib\plugins\vshare\syntax.php on line 209

**Comment by splitbrain** [comment]
fixed by #35
