### ISSUE TITLE
Question: How does it work with Privacy?

### ISSUE THREAD

**Issue by Mannshoch** [splitbrain/dokuwiki-plugin-vshare#36]
Hi
It seems the tool I need. But I have a question. I do not wish to let youtoube know about every site a user open while he is browsing through dokuwiki. Is there an Option to only load the video scripts after clicking on the video like the [Shariff Project](https://github.com/heiseonline/shariff) do it for social media buttons?

**Comment by splitbrain** [comment]
no. and it's not planned.

**Comment by tgroman** [comment]
You could try embedding hooktube HTML links, but its not supported by this plugin yet

**Comment by tgroman** [comment]
You could try embedding hooktube HTML links, but its not supported by this plugin yet

**Comment by tgroman** [comment]
You could try embedding hooktube HTML links, but its not supported by this plugin yet
