### ISSUE TITLE
add support to niconico

### ISSUE THREAD

**Issue by leeyc0** [splitbrain/dokuwiki-plugin-vshare#42]
I discovered that [niconico](http://www.nicovideo.jp/) has changed it embedding syntax, and vshare can now serve niconico by adding single line in sites.conf:

```
niconico        iframe  http://embed.nicovideo.jp/watch/@VIDEO@
```

As such, I am deprecating my [niconico plugin](https://github.com/leeyc0/dokuwiki_plugin_niconico). May you add this line in sites.conf?

Historically the niconico embedding syntax is too obscure that vshare cannot serve it and I had to write my plugin to solve the problem. Since niconico uses now standard iframe instead of obscure code, my plugin has finished the historical role and in favour of using vshare now.

**Comment by splitbrain** [comment]
Can you open a pull request? Also check if they support SSL and use the protocol independent ``/embed.nicovideo.jp/watch/@VIDEO@`` then.

**Comment by leeyc0** [comment]
Opened PR #43. Also adds support to Chinese video sites [youku](http://www.youku.com/), [tudou](http://www.tudou.com/) and [bilibili](http://www.bilibili.com/). All do not support HTTPS including niconico.

**Comment by leeyc0** [comment]
Oh I forgot to update sites.js for the pattern. I need to close #43 first PR first and will submit another later.

**Comment by leeyc0** [comment]
open PR #44
