### ISSUE TITLE
responsive value for responsive/bootstrap theme

### ISSUE THREAD

**Issue by EulogySnowfall** [splitbrain/dokuwiki-plugin-vshare#46]
Do you have a plan for responsive site for the vshare?

look at 
https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php

I'm working on it and will fork that if I've got something good, otherwise someone else did try it?

**Comment by borgendorf** [comment]
If it helps get this approved, I needed it so badly I replaced the two files from your Pull Request manually into my Wiki, purged the CSS cache (via the Advanced plugin), and it worked great! I'm using bootstrap3. Here's an example page with the responsive code working. http://support.darklightcyber.com/doku.php/tips:sparql

**Comment by ERTurner** [comment]
I also really, really need responsive videos with this plugin. I'm going to try and recreate the solutions above, but it's going to make updating this plugin a real pain...

**Comment by splitbrain** [comment]
sizes can now be given as `full` and `half` for responsive sizes relative to the screen width.
