### ISSUE TITLE
Embedded YouTube video appears and then disappears.

### ISSUE THREAD

**Issue by saurabhshri** [splitbrain/dokuwiki-plugin-vshare#51]
I tried to embed three YouTube videos in a single line, by aligning them all to left by doing `{{youtube>6VnhC8u_d40?small }} {{youtube>j_zeixo-zJY?small }} {{youtube>tFrf0TVnqIQ?small }}
`

While this seems (?) to work, I see the videos as I expect them to for some moments and then they disappear.

Here's the live version of the same : https://www.ccextractor.org/public:gsoc:gsoc2017:ccaligner_word_by_word_audio_subtitle_synchronisation_saurabh_shrivastava_gsoc_2017

![vshare](https://user-images.githubusercontent.com/12415700/29730399-a6f497ac-89fd-11e7-9607-7407ea546836.gif)

**Comment by splitbrain** [comment]
I just tried your page and it's working perfectly fine for me. Might be something in your browser? Maybe an ad blocker?

**Comment by saurabhshri** [comment]
@splitbrain Thank you for your reply! :) It is working right now because I changed it and laid the videos one below the other.

You may try the earlier revision, specifically _(https://www.ccextractor.org/public:gsoc:gsoc2017:ccaligner_word_by_word_audio_subtitle_synchronisation_saurabh_shrivastava_gsoc_2017?rev=1503692873)_ to replicate the issue.

**Comment by splitbrain** [comment]
Very weird indeed. I can reproduce the issue in Chrome. When I inspect the elements and disable the `max-width: 100%` CSS attribute, the videos show up. Funny thing though, when I reenable the attribute, the videos stay visible. I think this is actually a bug in the chrome rendering engine. I tried the page in Firefox and everything is working as expected.

**Comment by saurabhshri** [comment]
@splitbrain Another funny thing is, if you resize the page (ctrl + or ctrl -) the videos appear instantly and if you set back the zoom level to 0 (ctrl 0) they stay!

**Comment by splitbrain** [comment]
I can no longer reproduce this. Either I accidentally fixed it or Chrome did.

**Comment by saurabhshri** [comment]
Thank you @splitbrain !
