### ISSUE TITLE
Page with embedded videos jumps when hovering over Edit button

### ISSUE THREAD

**Issue by tmo26** [splitbrain/dokuwiki-plugin-vshare#63]
Release 2018-04-22a "Greebo"
vshare plugin 2018-02-05
Browser: Firefox 61.0

On https://openwrt.org/docs/techref/hardware/soldering#videos we have 3 youtube videos embedded via vshare plugin.

When I scroll down the page to reach the Edit button of the section containing the videos, and I hover the mousepointer over the Edit button, the page jumps down and with it the Edit button, making it impossible to edit this section only.

- Editing the whole page is still possible.
- Only the section containing the videos is affected. All other sections are working as expected, i.e. the Edit button lets me edit the respective section only.
- with `&autoplay`=0 it does not happen, i.e. no page jumping, and normal section editing is working
- with Chrome 67.0 this does not happen, i.e.  i.e. no page jumping, and normal section editing is working

Would be nice to get rid of that jumping, so that normal section editing works again.

Thanks for looking into this!

**Comment by MrReSc** [comment]
I'm facing the same problem. Is there already a solution?

**Comment by tmo26** [comment]
**Update**

Original issue (page jumping and with it the edit button) is **not** present any more with 
Release 2018-04-22b "Greebo"
vshare plugin 2019-05-27
Firefox 69.0.3
Chrome Version 77.0.3865.120

However, now with each hovering over the sections edit button, the preview-images disappear and get reloaded.

**Comment by splitbrain** [comment]
remaining issue is #13
