### ISSUE TITLE
Error executing youtube video

### ISSUE THREAD

**Issue by marcosviniciusb** [splitbrain/dokuwiki-plugin-vshare#64]
The following error appears as I click to play in the video: http://prntscr.com/l0hs0c
This is how the video was added: 
{{youtube>L-QwsgCnJCwy8&t=735s}}
{{youtube>L-QwsgCnJCwy8&t=735s?small}}
{{youtube>L-QwsgCnJCwy8&t=735s?large}}

Original Link to Video: https://www.youtube.com/watch?v=QwsgCnJCwy8&t=735s

**Comment by splitbrain** [comment]
Seems like your syntax is wrong. Should be `{{youtube>L-QwsgCnJCwy8?t=735s}}`
