### ISSUE TITLE
Playing with max volume (youtube)

### ISSUE THREAD

**Issue by shimmtak** [splitbrain/dokuwiki-plugin-vshare#68]
Every time I play embedded youtube videos, it is played with max volume. It is too loud to listen comfortably. I hope you consider a parameter for volume control.

**Comment by shimmtak** [comment]
I  found that the behavior was browser dependent. It happened on FireFox, but not on Chrome. I am afraid that I should close this issue, however, volume control parameter seems useful if possible.

**Comment by splitbrain** [comment]
I don't think there is any possibility to influence the volume when embedding videos. It's up to the end user to have a sensible master volume setting - I wouldn't rely on the volume settings for individual websites for that.
