### ISSUE TITLE
Autoplay doesn't actually autoplay due to YouTube policies - Please add support for &mute=1 to re-enable true autoplay

### ISSUE THREAD

**Issue by wad11656** [splitbrain/dokuwiki-plugin-vshare#78]
According to this blog post:

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Autoplay doesn't actually work unless there is a &mute=1 tag on the embedded video. Can you please add functionality to YouTube videos for the "mute" parameter so my videos can actually start? Thank you

**Comment by splitbrain** [comment]
all parameters are now passed as is, so you can add the mute parameter
