### ISSUE TITLE
Please add support for width=100% video player

### ISSUE THREAD

**Issue by kuzmandi** [splitbrain/dokuwiki-plugin-vshare#80]
Can you please implement the possibility of being able to automatically use the full width without having to give an exact width?

I would like to use _'100%'_ or _'full'_ (i.e.) like _'small', 'medium'_ and _'large'_ to use the full width, regardless of the template used or whether I use columns, etc.

Best regards

**Comment by splitbrain** [comment]
`full` and `half` can now be used as sizes.
