### ISSUE TITLE
We need some kind of consent (GDPR!)

### ISSUE THREAD

**Issue by ParoTheParrot** [splitbrain/dokuwiki-plugin-vshare#83]
Since the provacy shield does not work anymore in the EU, we need some kind of consent before showing the video. Isthis possible, @splitbrain ?
https://www.datenschutz-notizen.de/das-urteil-zum-eu-us-privacy-shield-und-seine-auswirkungen-auf-internetseiten-und-cookie-banner-1926622/

**Comment by splitbrain** [comment]
this has been implemented
