### ISSUE TITLE
Please add support for Panopto

### ISSUE THREAD

**Issue by actuarysailor** [splitbrain/dokuwiki-plugin-vshare#84]
I am sure many companies use Panopto for their video hosting; I attempted to do it myself but could not get it to work.  Note that **company** would be replaced by the company name.

sites.conf:
`**company**				iframe	https://**company**.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=@VIDEO@&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&start=0&interactivity=all`

sites.js
`'**company**':			'panopto\\.com/.*[&?]id=([a-z0-9_\\-]+)'`

**Comment by splitbrain** [comment]
From your example it seems that each panopto client has their own subdomain. That's not supported by vshare.
