### ISSUE TITLE
Vimeo now requires a hash parameter to enable access to videos with private permission

### ISSUE THREAD

**Issue by fquadt** [splitbrain/dokuwiki-plugin-vshare#95]
Vimeo has introduced a new security feature: Videos with visibility "private" cannot be shared solely via the video ID. A hash parameter is required. Please see this [Vimeo support article](https://vimeo.zendesk.com/hc/en-us/articles/4409305565069-Embedded-player-displays-This-video-does-not-exist-message).

The video sharing plugin could introduce a "vimeohash" parameter. This value is added to video url of the embedded player (ID?h=HASH)

**Comment by splitbrain** [comment]
The plugin now passes all parameters (except for the size config) to the video service. This means you can now add the hash to the syntax.
